default:
  artifacts:
    expire_in: 1 day
  interruptible: true
  retry:
    max: 2
    when:
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

variables:
  ucs: 522
  DOC_TARGET_VERSION: "5.2"
  CHANGELOG_TARGET_VERSION: "5.2-2"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  DOC: docker-registry.knut.univention.de/docbook
  DEB: docker-registry.knut.univention.de/phahn/ucs-debbase:$ucs
  APTLY: http://omar.knut.univention.de:11620/api
  APT: http://omar.knut.univention.de/build2/git
