version: "3"
services:
  updater:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/work/src
    networks:
      - frontend
    stdin_open: true
    tty: true

networks:
  frontend:
    driver: bridge
